const DEFAULT_CONFIG={profileName:'Ayush Mishra',displayName:'AYUSH OP',heroTitle:'AYUSH OP',heroSubtitle:'Creator · Gamer · Developer · Problem Solver',heroText:'Welcome to my personal space. Explore my work, connect with me, and ask for help whenever you need it.',aboutText:'I’m passionate about technology, gaming, web development, creativity, and helping people solve problems. I enjoy building projects, learning new tools, and turning ideas into interactive experiences.',phone:'9754478008',instagram:'https://www.instagram.com/yk._4yushhh/',instagramLabel:'@yk._4yushhh',telegram:'https://t.me/maybe_4yush',telegramLabel:'@maybe_4yush',discord:'@pandit.vidhyak',discordLink:'',youtube:'',youtubeLabel:'COMING SOON',twitter:'',twitterLabel:'COMING SOON'};
const cfg={...DEFAULT_CONFIG,...JSON.parse(localStorage.getItem('ayushSiteConfig')||'{}')};
const $=id=>document.getElementById(id);
function setText(id,val){const e=$(id);if(e)e.textContent=val}
function setLink(id,href){const e=$(id);if(!e)return;if(href){e.href=href;e.target='_blank';e.rel='noreferrer';e.style.pointerEvents='auto';e.style.opacity='1'}else{e.href='#';e.removeAttribute('target');e.removeAttribute('rel')}}
setText('heroSubtitle',cfg.heroSubtitle);setText('heroText',cfg.heroText);setText('profileNameText',cfg.profileName+'.');setText('aboutText',cfg.aboutText);
setText('project1Title',(cfg.project1Title||'Future Web'));setText('project2Title',(cfg.project2Title||'Gaming Hub'));setText('project3Title',(cfg.project3Title||'Help Center'));setText('project1Desc',cfg.project1Desc||'A modern experimental website with motion, glow effects and interactive UI.');setText('project2Desc',cfg.project2Desc||'A creator-focused gaming interface for videos, community and updates.');setText('project3Desc',cfg.project3Desc||'A simple place where visitors can submit questions and request support.');
setText('phoneLabel',cfg.phone);setText('instagramLabel',cfg.instagramLabel);setText('telegramLabel',cfg.telegramLabel);setText('discordLabel',cfg.discord);setText('youtubeLabel',cfg.youtubeLabel);setText('twitterLabel',cfg.twitterLabel);
setLink('phoneLink','tel:'+cfg.phone);setLink('instagramLink',cfg.instagram);setLink('telegramLink',cfg.telegram);setLink('socialPhone','tel:'+cfg.phone);setLink('socialInstagram',cfg.instagram);setLink('socialTelegram',cfg.telegram);setLink('socialYoutube',cfg.youtube);setLink('socialTwitter',cfg.twitter);setLink('socialDiscord',cfg.discordLink);
const loader=$('loader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),500));
const cursor=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}});
async function getPhoto(slot){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('ayush-op-media',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return await new Promise((res,rej)=>{const tx=db.transaction('photos','readonly');const r=tx.objectStore('photos').get(slot);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}catch{return null}}
async function applyPhotos(){const defaults=['assets/ayush-01.jpg','assets/ayush-02.png','assets/ayush-03.png'];const imgs=[...document.querySelectorAll('.profile-photo')];const cards=[...document.querySelectorAll('.photo-card img')];for(let i=0;i<3;i++){const b=await getPhoto(String(i+1));if(b){const u=URL.createObjectURL(b);if(imgs[i])imgs[i].src=u;if(cards[i])cards[i].src=u}}}
applyPhotos();
const profilePhotos=[...document.querySelectorAll('.profile-photo')];let photoIndex=0;if(profilePhotos.length>1){setInterval(()=>{profilePhotos[photoIndex].classList.remove('active');photoIndex=(photoIndex+1)%profilePhotos.length;profilePhotos[photoIndex].classList.add('active')},4200)}
const p=$('particles');if(p)for(let i=0;i<55;i++){const d=document.createElement('i');d.className='particle';d.style.left=Math.random()*100+'%';d.style.animationDuration=(8+Math.random()*15)+'s';d.style.animationDelay=(-Math.random()*15)+'s';d.style.opacity=(.1+Math.random()*.45);p.appendChild(d)}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const menuBtn=$('menuBtn'),navLinks=$('navLinks');if(menuBtn){menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')))}
const modal=$('helpModal'),openHelp=$('openHelp');const closeHelp=()=>modal.classList.remove('open');openHelp.addEventListener('click',()=>modal.classList.add('open'));$('closeHelp').addEventListener('click',closeHelp);$('closeHelpBtn').addEventListener('click',closeHelp);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeHelp()});
const helpForm=$('helpForm');helpForm.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(helpForm));const list=JSON.parse(localStorage.getItem('ayushHelpRequests')||'[]');list.unshift({...data,time:new Date().toLocaleString()});localStorage.setItem('ayushHelpRequests',JSON.stringify(list));fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(helpForm)).toString()}).catch(()=>{});helpForm.style.display='none';document.querySelector('.modal-intro').style.display='none';$('helpSuccess').classList.add('show');setTimeout(()=>{helpForm.reset();helpForm.style.display='grid';document.querySelector('.modal-intro').style.display='block';$('helpSuccess').classList.remove('show');closeHelp()},2600)});
const contactForm=$('contactForm');contactForm.addEventListener('submit',e=>{e.preventDefault();fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(contactForm)).toString()}).catch(()=>{});alert('Message sent! Thanks for contacting Ayush.');contactForm.reset()});
